### ISSUE TITLE
Bug fix + feature addition.

### ISSUE THREAD

**Issue by joeyhub** [derickr/vld#10]
Sorry for patches. I'm not really a seasoned github user so this is easiest for me :).

These patches fix a bug (segfault) and hopefully don't introduce any new bugs :P

This also adds a quick feature to send output to a file rather than to stdout. If remember, I did this to set up a vhost for a dev/review server that depending on the port switches between handling php as phps, auto_tracing, profiling and vld bytecode tracing.

It's a while ago since I did this but I think I just overwrote the stdout support (unless its set to the stdout fd by default or something) :(.

I think there is a possible compromise on performance in this.

**Comment by derickr** [comment]
This no longer applies, and hence I'll close it.
