### ISSUE TITLE
VLD is invalid library on Alpine

### ISSUE THREAD

**Issue by AlexMasterov** [derickr/vld#30]
Strange things happen on Alpine Linux (Docker) :confused:
It works fine on Windows and Debian.

PHP: from [source](https://github.com/AlexMasterov/dockerfiles/blob/master/alpine-php/7.1/Dockerfile)/[package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/php7).
VLD: from source ([VLD_0_14_0](https://github.com/derickr/vld/tree/VLD_0_14_0)).

How can I help (debug) for you?
```sh
# uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 Linux

# php -v
PHP 7.1.6 (cli) (built: Jun 12 2017 21:23:32) ( NTS )

# php -dextension=vld.so
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'vld.so' in Unknown on line 0
```

**Comment by derickr** [comment]
How did you build vld?

What is in vld.so? Try "file vld.so" (in the right path) and "head vld.so" (in the right path).

**Comment by AlexMasterov** [comment]
Thanks for the quick reply.

```sh
git clone -o VLD_0_14_0 --depth 1 https://github.com/derickr/vld.git /tmp/vld
cd /tmp/vld
phpize
./configure
make
make install
```
```sh
# /usr/local/lib/php/extensions/no-debug-non-zts-20160303

# file vld.so
sh: file: not found

# head vld.so > /vld_head.log
```
[vld_head.log](https://www.dropbox.com/s/iotk9ny3jxb2y2v/vld_head.log#) (sorry for Dropbox)

Btw, Alpine uses [musl](http://www.musl-libc.org) as its libc.

**Comment by derickr** [comment]
```
# file vld.so
sh: file: not found
```
You do need to install "file" for that to work :-)

But at least the "head" looks like that it is a shared object (ELF) file.

>  Alpine uses musl as its libc; musl isn't 100% compatible with glibc, hence the missing symbols.

You didn't include these in your report, and they are important to see.

**Comment by AlexMasterov** [comment]
Oh, Alpine and me. Sorry :blush:
```sh
# file ./vld.so
./vld.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

**Comment by derickr** [comment]
I meant the missing symbols! I need to figure out what musl misses.
