### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [derickr/vld#36]
https://travis-ci.org/derickr/vld/builds/463298978

**Comment by derickr** [comment]
I'm not too worried about this. VLD is notoriously hard to check in CI, as the internals change so often. I might just be better off turning CI off for VLD. Thanks for the pointer though!

**Comment by DanielRuf** [comment]
So far only the posting / upload seems to be the issue.
See https://travis-ci.org/derickr/vld/jobs/463298979#L1150

No CI would not be great.

**Comment by derickr** [comment]
On Wed, 30 Jan 2019, Daniel Ruf wrote:

> So far only the posting / upload seems to be the issue.
> See https://travis-ci.org/derickr/vld/jobs/463298979#L1150

Nah, all the tests fail too:
https://travis-ci.org/derickr/vld/jobs/463298979#L1131

> No CI would not be great.

You'd be more than welcome to fix the tests :-)

cheers,
Derick
