### ISSUE TITLE
Compiler aborts on uint

### ISSUE THREAD

**Issue by kainabel** [derickr/vld#38]
The MS compiler can't handle uint 
https://github.com/derickr/vld/blob/master/srm_oparray.c#L550
[vc_uint.diff.txt](https://github.com/derickr/vld/files/3125660/vc_uint.diff.txt)

**Comment by derickr** [comment]
Please make a pull request.

**Comment by kainabel** [comment]
> Please make a pull request.

Oh, unfortunately, I don't have enough knowledge and experience with C and Git.

VC for example doesn't complain when changing from `uint `to the predefined internal type `zend_ulong`.

Refers now:
https://github.com/derickr/vld/blob/master/srm_oparray.c#L562
from: `static uint last_lineno = (uint) -1;`
to e.g.: `static zend_ulong last_lineno = (zend_ulong) -1;`

Please don't misunderstand, the effort for me newbie is just too huge to get two mini changes in, which they understand much better. Please just change it in your own way to allow the compiler to run.

Thank you for your time.
