### ISSUE TITLE
How to see opcode after optimisation by Zend OPcache

### ISSUE THREAD

**Issue by lyrixx** [derickr/vld#41]
Hello @derickr 

I'm able to see some optimization on CLI, but I guess some optimization are done only in certain context (FPM). 

So I wonder where can I see the output in the web context (with FPM) to be sure some optimisation are done (or not)

Thanks

**Comment by derickr** [comment]
Sorry, I've only just now seen this.

As long as you have `opcache.enable_cli=1`, it shouldn't matter whether it is on CLI or in FPM. But make sure VLD is active after opcache.
