### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by petermcd** [derickr/vld#45]
The following tests fail:

- Test for jump calculation with catch() [tests/catch-php70.phpt]
- Test for jump calculation with foreach() [tests/foreach-jumps-php70.phpt]
- Test for issue #19 [tests/issue00019-php70.phpt]
- Test for issue #20 [tests/issue00020-01-php70-64bit.phpt]
- Test for issue #20 [tests/issue00020-02-php70-64bit.phpt]
- Test for issue #21 [tests/issue00021-php70.phpt]

**Comment by petermcd** [comment]
The 32 bit might also fail (I am running 64bit so these were skipped)

**Comment by petermcd** [comment]
After looking at the tests it is clear that the output has changed significantly from when the tests were written to the current version of VLD.

I suspect the only potential way to resolve this is to pin the tests to a specific version of PHP otherwise new tests would have to be written regularly to account for changes.

**Comment by derickr** [comment]
Yeah, all the tests fail due to frequent changes in PHP itself. It's too much of a pain to maintain, so I am just going to close this issue. At some point, I'll fix them.
