### ISSUE TITLE
Display for NEW does not mention classname

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#47]
When there is a class, we use vld to dump the instruction, we found that the dump result:  
20     0*       NEW                                              $2      :17
The operand is only :17 ? How to get the class name by ":17" ?

**Comment by jimmyleeeeee** [comment]
Nobody answer ??

**Comment by jimmyleeeeee** [comment]
Thanks a lot. The issue has been resolved.

**Comment by jimmyleeeeee** [comment]
The issue of  NEW instruction has been resolved. But , today, I met another issue.   The php code is 
class CConst{
	const MIN_VALUE=1;
	public static function getMinValue()
	{
	    return self::MIN_VALUE;
	}
}
$const_var=new CConst();
$c=$const_var::MIN_VALUE;

The dumped code is :
  10     0*       NEW                                              $5      'CConst'
         1*       DO_FCALL                                      0
         2*       ASSIGN                                                   !0, $5
  11     3*       **FETCH_CLASS                                   0  <unknown> !0**
         4*       FETCH_CLASS_CONSTANT                             ~9      $8, 'MIN_VALUE'
         5*       ASSIGN                                                   !1, ~9

The return of FETCH_CLASS is **<unknown>**.

**Comment by derickr** [comment]
Please open a new issue for that. This one is closed, an they are unrelated cases.
