### ISSUE TITLE
about the function of traits

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#49]
Currently, when a class (MyHelloWorld) use a traits（SayWorld）, there is no any opcode to show that the relationship between the function of the traits and the class (MyHelloWorld).
The example code :
```
trait SayWorld {
    public function sayHello() {
        echo 'World!';
    }
}

class MyHelloWorld {
    use SayWorld;
}
$o = new MyHelloWorld();
$o->sayHello();
```
As the function of the traits (SayWorld ) can be called by the class (MyHelloWorld), there must be some infomation about this.  How to print it?

**Comment by derickr** [comment]
VLD is primarily for dumping opcodes, and it does not try to show all the information about a class. Therefore, I think showing this information is out of scope for VLD.

**Comment by jimmyleeeeee** [comment]
OK. THanks for your quick answer.
