### ISSUE TITLE
the instruction of vld is not correct for php7.4.0

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#50]
When I use php 7.4.0 and vld to generate the opcode, the opcode is not correct. 
The php code is below：
$a=1;
$b=1;
echo $a!=$b;
echo $a<$b;
echo $a<=$b;

I get the opcode below:
line     #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   2     0*       ASSIGN                                                   !0, 1
   3     1*       ASSIGN                                                   !1, 1
   5     2*       **IS_SMALLER**                                       ~4      !0, !1
         3*       ECHO                                                     ~4
   6     4*       **IS_SMALLER_OR_EQUAL**                              ~5      !0, !1
         5*       ECHO                                                     ~5
   7     6*       **CAST**                                          0  ~6      !0, !1
         7*       ECHO                                                     ~6
  35     8*       RETURN                                                   1

It seems that the opcode is not correct.  != is translated to IS_SMALLER. <is translated to 
 IS_SMALLER_OR_EQUAL.  <= is translated to CAST.

**Comment by jimmyleeeeee** [comment]
I have resolved this issue, may I submit the code?

**Comment by derickr** [comment]
You don't need to ask to submit a Pull Request, just do it! We can then argue about whether it is right or not :-)

**Comment by jimmyleeeeee** [comment]
I don't have the privilege to submit a Pull Request. Can you open it to me?

**Comment by derickr** [comment]
Everybody has that privilege, it comes with GitHub. But you need to do it from your own fork (see top-right button).

**Comment by jimmyleeeeee** [comment]
I am sorry. I don't often use github.  Thanks for your guide. I have learnt it and tried to add a pull request. Please review whether the change is OK.

**Comment by jimmyleeeeee** [comment]
I have  create a pull request, please review whether the change is OK.

**Comment by jimmyleeeeee** [comment]
The issue has been resolved.

**Comment by jimmyleeeeee** [comment]
As the code is noe merged to master branch, I reopen this issue.

**Comment by derickr** [comment]
Thanks, this has been fixed through #55 (by you :-) ), and it's now merged.
