### ISSUE TITLE
The return of FETCH_CLASS is <unknown>

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#51]
The issue of NEW instruction has been resolved. But , today, I met another issue. The php code is
```
class CConst { 
 　　const MIN_VALUE=1;
　　public static function getMinValue()
　　{
　　return self::MIN_VALUE;
　　}
}

$const_var=new CConst();
$c=$const_var::MIN_VALUE;
```

The dumped code is listed below.

```
line　#*　EIO　op　　fetch　　ext　　return　　operands
-------------------------------------------------------------------------------------
10　　　0*　　　　NEW　　　　　　　　　　　　　　　　　　$5　　　　'CConst'
　　　　1*　　　　DO_FCALL　　　　　　　　　　0
　　　　2*　　　　ASSIGN　　　　　　　　　　　　　　　　　　　　　　!0, $5
11　　　3*　　　　FETCH_CLASS　　　　　　　　0　　　　　&lt;**unkown**&gt;　!0
　　　　4*　　　　FETCH_CLASS_CONSTANT 　　　　　　　　~9　　　　$8, 'MIN_VALUE'
　　　　5*　　　　ASSIGN　　　　　　　　　　　　　　　　　　　　　　!1, ~9
```

The return column of FETCH_CLASS is &lt;unkown&gt;.

**Comment by derickr** [comment]
Can you please format the text in your issue? Have a look at https://guides.github.com/features/mastering-markdown/ on how to do that.

**Comment by jimmyleeeeee** [comment]
I have updated the comments by referring to https://guides.github.com/features/mastering-markdown/ . It shows good in edit status. But, after I save it, it doesn't show well. I am confused.

**Comment by jimmyleeeeee** [comment]
Hi, Derick   I have updated the format. Please review whether  it is OK this time.
