### ISSUE TITLE
vld.verbosity parameter doesn't work

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#56]
When verbosity is >=3, it doesn't print more informattion as respected.  It print the same result as verbosity is 0 or 1. 

The reason is that the API for update verbosity is not correct. Currently, OnUpdateBool is used to update the value. In fact,  OnUpdateLong should be used to update verbosity. I have fixed the issue and submit pull request.  Please review it and agree to merge the code.

**Comment by derickr** [comment]
Thanks, this has been fixed through #55 (by you :-) ).
