### ISSUE TITLE
For switch-string, if there is special char like \n in the case, it will print in another line

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#59]
For the code below:
case "\n":  $out_string .= "\\n"; break;

The \n is not encoded, vld will print the opcode after \n in another line.  When print switch-string table, should encode the key and value.

**Comment by jimmyleeeeee** [comment]
I have fixed the issue and created a pull request. Please review it.

**Comment by jimmyleeeeee** [comment]
@derickr  I know you are busy, can you take a little time to review whether the code is OK?

**Comment by derickr** [comment]
I had merged this on April 14th already, but I had forgotten to push my changes to GitHub. Should be there now, and thanks!
