### ISSUE TITLE
When the code line is over 10000, the lineno column is not shown correctly

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#61]
When there is over 10000 lines code in a source code file, the column of lineno is not aligned. For the lineno less than 10000, it occupy only 4 bytes; for the lineno greater or equal 10000, it occupy 5 bytes. The column is aligned.

**Comment by jimmyleeeeee** [comment]
@derick  I have fixed this issue, please review the pull request and check whether the code is OK to merged to master branch.

**Comment by derickr** [comment]
I had merged this on April 14th already, but I had forgotten to push my changes to GitHub. Should be there now, and thanks!

**Comment by jimmyleeeeee** [comment]
It is OK now. Thanks.
