### ISSUE TITLE
flags != OP1_CLASS;  

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#64]
In srm_oparray.c line 636,
  
flags != OP1_CLASS;

This is a comparison sentence. It is useless here.  Is it a mistake for flags |= OP1_CLASS; ?

**Comment by jimmyleeeeee** [comment]
@derickr     Do you have time to confirm this issue? Thanks.

**Comment by derickr** [comment]
Duplicate of #63, and also incorrect, as the line this is on is 598.

**Comment by jimmyleeeeee** [comment]
Thanks for the confirmation.
