### ISSUE TITLE
When the op of the new is variable, the dump code is not correct

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#65]
when the code is below:
class Test
{
    private $_walkers = array();

    public function addTreeWalker($walkerClass)
    {
        $this->_walkers[] = new $walkerClass();    The operands of the new is  <unknown>.
    }

     public function addTreeWalker1($walkerClass)
    {
        $Classname=$walkerClass."Service";
        $ServiceObject=new $Classname;     The operands of new is 'Service'.
        return $ServiceObject;
    }
}

If the op of new is a variable,  the operands of new in dump is not correct. Some cases the operands of the new is < undef  >, sometimes, it is < unknown >, sometimes, it is a string.    Before the latest update, the code can be dumped correctly.

**Comment by jimmyleeeeee** [comment]
when the code is below:
class Test
{
    private $_walkers = array();

    public function addTreeWalker($walkerClass)
    {
        $this->_walkers[] = new $walkerClass();    The operands of the new is  <unknown>.
    }

     public function addTreeWalker1($walkerClass)
    {
        $Classname=$walkerClass."Service";
        $ServiceObject=new $Classname;     The operands of new is 'Service'.
        return $ServiceObject;
    }
}

Some cases the operands of the new is <undef>.  

@derickr  do you have time to check this issue?

**Comment by jimmyleeeeee** [comment]
@derickr please help to check how to resolve this issue?

**Comment by derickr** [comment]
Can you please stop continuing to ask when I get to issues? I get to it when I have time, and that gets less likely when poor quality tickets.

In this case, your code doesn't format, there is not original output, no pointer to what goes wrong in that original output, no PHP version, no mention on where opcache is on or off, etc.

If you create tickets which explain the problem clearly, then things will go faster, but still only when I get to it.

**Comment by jimmyleeeeee** [comment]
Hi, Derick
I am sorry that I don't make this clear.  I hope it will be clear this time.
I have formatted the code as below. 
`class Test
{
	private $_walkers = array();

	public function addTreeWalker($walkerClass)
	{
	    $this->_walkers[] = new $walkerClass();
	}

	 public function addTreeWalker1($walkerClass)
	{
	    $Classname=$walkerClass . "Service";
	    $ServiceObject = new $Classname;
	    return $ServiceObject;
	}
}`
I also upload the code as attachment.  
![testcode](https://user-images.githubusercontent.com/31074398/90478109-2ceb9200-e15f-11ea-8bb5-65388a3c6bfd.PNG)

The PHP version is 7.4.4. I run the command "php -dextension=vld.so -dvld.active=1 -dvld.dump_paths=0 -dvld.execute=0 testcode.php" to review the opcode. 

For code of "new $walkerClass()",  the operand of the new in opcode is  <unknown>.
For code of "new $Classname",  The operand of new in opcode is 'Service'.
