### ISSUE TITLE
Support Ioncube php 7.2

### ISSUE THREAD

**Issue by PoweredByAndrox** [derickr/vld#73]
Hello, i tried to use VLD to see opcodes but the after zend_compile_file returns opcodes == null but the vars exist ![image](https://user-images.githubusercontent.com/38520826/150280435-5819c9f8-9821-4501-81ff-47a50b2dff5b.png)

How i can see the opcodes correctly?
NOTE: the zend_compile_file directs to the php_ioncube.dll a function callback that decode the file and return it

**Comment by derickr** [comment]
I am not going to add support for ioncube.
