### ISSUE TITLE
Can't dump ionCube codes.

### ISSUE THREAD

**Issue by danuonuo** [derickr/vld#76]
**Describe the bug**
While I'm using vld to dump a ionCube encoded php file, I found that vld just returned "Segmation fault (Core dumped)"

**To Reproduce**
PHP Code:
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cP/elNcdunA9EzShBIac19casTjZGDaW9AFMEELOcX9C5QfQMTx+W+I9ZWtkmTvYINFOZskwD
+yQ3HAmLwSRGUPKR2pf2MNEyilOSX0RHf5+ubZ4NC7tptGVtZKpCAAjdg6hn+Pv0TOhf5k/SucA3
L+bXAtUAb57vo++5wOfmZkSO+H6GyUVwHWDGfSH68V2wiJ4T3xzhOx32YxMwacOSaVobN5jP5qPE
7ROvDiGccLqpv5+VaCjd7MwO8xAoLsCzBDeAO+S6V5UsS9SeuzJDeVdrL41q4aV4GEyIqE9/sVZm
YHiBNNKWYqQQIkye0m6hUGTaO07/9uwpvA+OxMxsZKtnrjrkYtLbivbaULIpkvE/RlXqtDhf/PN7
zL8i/cTSsyMEduNV3h/zURy+Np51dGyg2n64Z2HLL6kAq4+Iuu/p5TWmjvjEb6tSc18IDysI1WKJ
UH+CxvA9RBfL3MTu0C2SvHxVyfryR6qFD8/FiYthtpL8i7h4h564SBZxI+WMcjOw+LJLLb2R8uvc
eFjnqc1CBz1PHd7zMJiUlRSE48HXjSiG/feKjx3Q/T3G2tI3aVzCyeXPRUq/kbvqSSAfpODC6TJF
pMCFFm+9c4VpD+K0OI4v9YCmjxBXhmzGksgp21yQGgD5EZRYYnWdJjEKj9wxuNw8RF+dID4gyYc9
sJzg0DWMyNtHLULhdiAHZzj9je8Y7lPLNBcdNMOuHAmQQLd5BLZyRoR19MPGHriiZPdkRGmSuDjv
jQtHGyrkidYRDkEgIuZ3XMR/Zq1jQGvs290YxT9h60Sb3qOuRqqaPaWP2v/89gL6oajH+4Kv7XMM
+2HwmqUt+CK9MioAo+iwcklA6+bkOS3hPqFtCQu0yhAohhg7J19wDQlTj75xHwDpXKPMgM5hf2Pb
OI4JRIEhy6X84z6jLapYAPesD2BaKtS+O8K2MHH+00WDHB3rL34fEyB5VMKQQQFOJs+a9YpjjRBc
741lDXf1jAPR5lTfw1atqFg4YdOUDbvbCURMnHWgq7xCwDPi/AJeJW0bJHgaXF6tloTGst87NT/H
czyZXkkM8OV0EWlrGDUseHBVs9wHLiWPfQtWGOtiMV9fxJUCM+W37zPDHHUKEuctndZUZUPF7/hs
ffXDV6vE8phShtGr3cRReYgtCvLPq7ZG0km1naLvEWxeAc5odJr3Jf/vUqaNELpS0OhTiMLEpHnS
V9clx92CykGfW1mtUSdWxT+ZETnvsU+0U9vnc1VYwrudDoGFvKrho7gxmzYYWJPCmgd0esBYuZAU
y65HG8HE9n/8nB2Q5/aR+hpLiMqtyEnb34m5Ant93UJsutm8CCl7lNwWA3sgENWTogDcPMR/y6kV
sXCUQwZOMXglQlOfGYlPyUTUcaKqZesf4mweKmc7FNsTpCIGaHMXayIKQxWVBPz86FxA5N3FXfCQ
0u3c/J/8zhjtKnYkXzsjbUiAnuQN35iHQwVw4ct0kueA/Rcu0LNlxjztOVjfwAgEKqXzrWpRjst9
X5HqIwWL47Yiu9hInekSWTDzdCCap3PZDmcPwPHnKY5t2r4Q4DK1LxZo20J+ZMsqhtokfz5x7Zix
v60JogzJCHrMYmLDSebnqHuM+SzWrsYspES/288/i6a72jOKMirVPv2/1+iCDStuUpXvp0YWtg0l
OTQt1wDgx2B0S0V0sugiXCM7bz13tgHvL0KKkCy37vJ2XS9CUhb7uGG4UiAimDcYrZtpejK8ZgkH
TfoLe+itSwyfejR8O47cEQUh7ZWcWe+mSUtYOAdaExoZeAhq1ePinCQZjFQu3P6q049fivDIV4lA
WZYl6A0xyjKM7LB2stWeQwzGQnwrzzaLmkIdr5LaQAXFHoDsBc6APVM7I84HZ1niVUfvDMiqyKdP
ROta483LYHFgY1QULmEYCm+HP5FPCPA0EZ9H3wOKgTuW1QgwhrahHioAT7HdPLOBObQvByRFPZ4+
NltmQANoRJRGA5Sx29icXGwHSteI7e18iP7r5qxeQRbsndkIjKYAbgbm4/2RgchPODbPiPR4aRlu
PZxj8byEmOSzPluX/6HtSFT83iIsuYmxFjRdBHJL/0aDS9L7KJS1TCnNElSVyzYg4t5/Cq5K2kXU
tGYSIrswWOfL+5jPMvqZhb8sXBndU2UhLBYEZljPdTguN9JzCocCVCrfoO9ZBvy17VqfvRMCBCVC
aGjn4hU3hbd1dbR50casVYx5S3N7hKPT1focYEDMz+krOWN30RIIG07rE8VpFRRAppXacYLUwbsp
kFr2dNDdyrSHHkWIr4yZtg4hMvQToWN5PxtRLvVrOKG6zz6WFhH3sAN5RCrIG0/MaC4Ba5chfCB5
V0e0pNqb4rl8Yz/r93g28l35r+ECrv+CU0vXHJam/fjXroee2jYb8KhyIx8MAsM8A6fI17JWevRp
pZvYNw+4Wvxqb+mxAKpAzGDs7fVTvod8vtVBJrSFbNM1t38k28VWrpZ+XxDBbiB5wynUw6juEP6u
ciX+fi7972/aJPywZwDJeANT68hg00oO/Al+EmzS5H802js0Zcyu33ETeJLuXYjMSKVvKcgjdAkq
Vj1+jX5shbnVlhgPYbEWutnAKL8ohKX+Dmzky+QH0t2z6qJIg5sFZ7nR/46CoMFDX7M3T+lv9uoV
0wuWkHDWpVpPTx8XbJrvZZz7c3rKR7XBfS4jxnQJcTEnBGJoAcJ1Cbib/Qnhc4VT6/R0SkV42/nX
/zq00IVZkgRjCNDxYcGd9QTOi3uAQtUOHlV23T9dffu+AmA2QOjLFV40zzHMl7KRa+a+GC41FzGe
IJ8h3tHJWp2I3M48Y/lsTKJWrl5sIh6BaDyxAhlWVFnzHeGxws8izUCsV4+j2UH4jrPe1LdVnI5F
HhkXB6meC+WMaAR9jKqGgvQxi3YTYbHs5eMWHNO0CvlEz7i9Bha4psW2v3+MSN7/HAUAnWdnVfVt
lxJaEIOFzBoKPnaR9jRGdJVPccDtAqN3S0XvaXcpShjjXSsz81raao/4qE2n6bfjUlZKnSfYDgfy
fgXx66r91PHIhwdEyxQCHIiETZ6oEPNN45810PUrZNxJBPezn3zaQ06feWNFjFKPnFAlFGKzHVyp
MucijmKqzUfdMy6rPx5YxOEXPDIkuyG6GfCRNJkmTIZS1+vFxvi57S7UHbC87jMoquW5yfofSXur
DncGcVlMoUJRkDF4UvlKsUcfeuX1HzF0/0dwbRZ6bVLYt7NoVpYKwo517bVqXwB5BrrGRyWLdpMq
0Tvgnxjbe5Rug2+rQFhv+MWwky5pXBYrx2dOQyg0bZztizyOd8R2aUerwunOI6+j8SGtnH5LtaDR
rx1d0W4QJ5Xf1s8z9LA7kdTRxR4RCSyLnGBoB6qhiIVFngCcmJxZBxbCs03h+NJsQJFJ4J9S8/vR
keUbCzPDT243MA1OV3I8aNLNyRjB8TgpP3b0MdURvJzUNrgFkCwkmsnI6VJLJ+WRqMtmlAstpARI
G8B2/SzkHq7oLJWDLEzlzHH57rAQOcBg6ZKQ+fdLyY1y1VX0a0EzGJrUb415seAj2tP5/gQwJfeg
obr/fO1O7ptZeoa1yfpRwdc/oqQJhlSdGo+qEzmhRfwtI1wNvtvJyKpx9qRJykc1RjI7m3OS6Om+
KuE2CQ6SJtkbsc15dmz/8eBD0Av6rQoX9MIWZCafO24dnqE+ejSw3yDkyMkJy+NZf2QVX5H3IIol
fLOomIBj6I8MLllFCPUjnKwlum+zTTZhZwS/koz5e2kvyXIdqJUz3+z1QSUHZ9Kk+ZOxXrY6O1XK
qfhla3tswq+Ce/Uw+HBhpNwZC+0nGIrHT2hxJVeFecDyVOIk+HdsiX0HkbQkiLHgiXV5HSMLhff9
O/lSCBRf7/0ZP2kHuhbKPo9zbjLROZ7TyOy4EC9acMElXZWxAde6fbY/VHAp+WtQkvWQeXzE4tY3
YmzMgaPjG2kklDquevNxdV5SYAnveZZ49DGBlomdsZr6htEFqGroTugNuQOvrHDYjAetHnD4IxKV
eA4E13zSpZy8h//DIE9sWOMs0BUX8es42FErA5anACJY3wBD1fMMCMQr0FjVXItH4JL7KlflZWx2
dP80YxZ259Hy0vqsU5MY8s8Gy92IelhO0w72v8BouHrJ6N4oWSFHBl/5oDkkwP6Vb1XR0IPr2AYs
zjjwPAcD0pXoryru2pFpoYhYSWIlQBwDHtFa479iItZ03SKf1Bc7He8KULe7IegWWrUlTlWv2zsK
+U8Q28cqADeb2Zb9d0RhlB/6joHTxh5MUUQ5dY1mLQpb5Qa3+hfCJ6ExiH+ubekcV4ROFREX6Wr4
UP4TcL8s0nchRleXqiwZT9GwwgrdY2WXS4POCV42/GBC/DLQiqm5oPDapWQeW0PksPYpZjxj2Imz
2Pz6Vyv9CC5I2EAb0HYPVkVL3mawnpFp3FaHu9B1G+ZeQhlsihMBdfMbkRMMRE/0VzdHpGGCDvHT
w1KD5Kj8X4bXhkvd7C/3iSkelq+5lrWRo1bMkFeWzihKCCfkVQpbE+E7xr7IR/EH8nuj9tXlu4LP
GO/NNLtUdaXFiDnb0Dl1obVOfuDRaG+u/a2y1cfLvRfUS6FxhDQaQG3v6UrtK1w09swRn9JlgdIf
A6VdF/BYocfxG0IcR+on/T5RDRPv/ITH+nGhZU7c1NkxsYH0/OVc9RKQdeepbnKR2L4oZCRD0DjG
6Y+l48jzZib98Cq69CV9cLZ4neqveV3MxhZk5cVRyMCJDi0ZGzpPioYjQO7jhxHZOvEfp9BbiNqt
fngykBg9v84AB4CrkCpKHPep0ShP0W6krbFMaRuO3z6gOTQ1d6vXe1Ie5RtiX4nn8Oc1pwwWK0H8
M5MorOQvm2S0FycoA93ym7k656uP0Sq3woVsjoFpX9/g3UKZZIPz/GNfEAAn4AAMomZ1YPWqbpTl
QuVZorljdCJk9Eg6i+f8MBiDogNISNnGDfyuW25K6+EYWN5AaXMxJ1nDFRKSQ2MCV7k70xDqzYUd
vFMbCgrG0yXWll0l8yY7cJFzH6xXvtbYohb2ADE7L9RgG2XC3D6ErtoztG/WVNnnlF1Qo7gSmVbL
KY97o4rg3szjbJRRA2juYiUgv+D25KztTbVzp7n8hFdg7y4fKr0xwUpHZm6b5tsFRJ6xBNPhkYvM
VoeNcF7ObAgymeDu+ifHctra1QzKt9LeSgplKLxJ+97Hg7wOuZUVQKJweemMlaY+bM/wu/sLfn6U
cqEY8mX+DgVGCFPHSm1QFWtkMZi6ANDX43/aihT2A/rPqkjIMl53oA9adzaJ72aFgbpR5u+NE0d8
XiHN4QuOjX0cDX2F7rGmXPBrwdbsy5+RPdFINVmZ5ZswMGzNaHWovw7FSaacKuv98cRA9EBPn2CX
/2gs4JXxU8jtPH+vkQDFeTKGGFtdyyZP7AwfaivA0labYeXOJrciv2xqEC4oiHMX6/TGj93h3TBA
NysySNdK8VYJR6DsaPYdHrDX1MW3dlqRi1KQ+pTujvz2FkFufdrXh1MIaVagCeY2kTL3CpE5mqC/
mBesctepOM1JfeIcI8QURfc6YhEE3qoJRDmTnXBWA92DqIsu9adH8AHDHM0ZMNuiV7awLU1xI6Zk
Czx2rTblebmoESEpqM8hx11EYXJgLIzWwKOwChexb0hpejf1QepV2+GuuLqZE2wawMiSZfUpzUiX
EflmiLXOVRxov4P68pzPBiqcEAAd8EH/klzdfyHq9vL51b8zZvSr3Of8gcZybkvx6P5W5LSSnF7s
cFwrqgjO1o9i58bZirXF0vQR2oCFWa+wyuwZqm1XmivHFaHzWzfiEQ4vhSAvVWaYnCJc+ffDbl1N
/Yif4HN5eD1kUByfXKBSoIvqtv4jQ1NBKd3iCWKQ8JUHwqC+D1XA3tR/5TFz/Xag9dusUfk5z3by
NAxq54oUsRH5/c36XB8E8AF7HoxCdFsFiig4IUM/+T409a2eY5tfskX04Jvb49eI2b810d4/7s+5
jmhweuYKissHbRbUAEZsLyN0mjUUsU2gatDI509W3L2/gur7BUgiGwtF8L5f/YY65V9UIeuVse/g
IUOmckGmpZKtO9mQru/Zz3kAIu6onMqTsn6O1MJ2qAVX+/X+JGcUFbwD7BWcy2JOIF5CfL+fx3uX
J2P7QYGeVRCfstsF0Mqd5I4NcgzZK0ngJsQuSZr5cyM+DEHuAN6tY4MdipUd89JP7r61HpKmgmFo
45JPfzh7ophb0yup3BZBakwLWmngzxfqNH0le9IiYeNSuJEF/PtlDo3gFp3bOheQJoDGEI5PK3s7
uSJGX7NBs2UlTzPGmdnpdw6CqUspTiuCR8xFQRN+hs4dt04XELAGX8eQKntPoBaAe6VbUHelDRC+
YLVzO3HxTErkI0XGRG7k/rHOgox1KBlSSgfbG/3Q4tj+CAStYAT5dPbDGEAxe1fBJABpqy3rsYPu
Dwv8ZNHU65NZL8RMq6YDax+XS2rXKprKs/ePZ4rDHkluRL3+8LPLBM/9KrPtPRlHmKVMQfCtqC0Q
WKhRvyY3+mAW0Nlve4yDR0U86rZ2BdVjK6YiOhikpDi61yOz4Kr2RQ2Gc71gdDeS3Fqllt9I2vsp
lHHn5KOiR+TQ/ARwAJFtfCxY2+4NBmkV3PsnrfYNHuVwIqZl7Q6Bu00/peWkeYn7XmCE5K9mtK4J
K9IqqSmYaLqxc7KPm7cmdQFqoYUptu1rxIQQRxMStz48n3GhdI2TVZ5NpZEwpfmOplnW6+6xBPqo
3DclzRVUjFQ12d1iEf/ecjIGctnt3AC20Gd0xgSppOe71s9l5iq8vh4FlPtaGcCo43lEtP/zv1Gt
HZuDPn1VjxNjQhDB1c0gqNkhH/NAudcB3E4ZCEHdlt+gBQlYsMu5eG/ko/1u/RGN8nOJI5+FEdDe
xmMktSvk5F6LTHVx90y1Y6Nq7nXL+09XqL/rcigitsA5f1L4MwBDWCr+SZ3c6Tv70x7MSu78pX+a
vwtjxtj6E3SHChTksoBej7YYvkcByw5ZUCiPr4BgJqN59snAThvbtuZTkWtaxtE3vfWf1QbJQnCe
cBaOJ3SktKdBN5jysnGkM0uHbEx/1iDdrBxuxxF+pJ9Pj45Gmb4gI/OsyOrc7xwsbRPOR2EenWKp
Rd1p/Ezzy21w5KLIAs1Nso9VdMeQzsqCRhQuLd8fR27Rv64KYf3m7lhnhfnebZfbdiEtz8znFJdx
ekgLjW8fG6lbe7Y9HqXKNo4Gt34JoZzVM7AdxzZ+Vrpmwi8bmaelqorvlHIBXyMXvqON0FzXeSZQ
40nyC/DvjBCJitv4Uet8vZO2bDKp7jwuQhGPOhYCpcfTmcjmgzy6geWC/Tc6/HZs69PkHYJXeWS4
k24Ctbi+SL1nVA/So+TzWEkHwf+6ZB9jTbYdwJhU5myZg5CxXLcVjoi41kusJyLI6URwEE2GPzSs
ES0Mpvwkm1JWpgGxQQPHkkxWmW2diSTms/x8yAMt/GcWmbspcQJJ+XUAxGH2Jc7aqWBE1b43hffl
TrRLxDAbD8feEUXwhZId2Nd8ClVsolyc0kUqMg5H6j2Xyzaxxp+3+EVM19eat82xv2EPaeaXQjkv
QTB7AN1MFJzcCqh2moN5bRVHisvq1q1P/tXmyOCkvzX7qmWOrRyDKCVt8ExavsOETU7l85EW3fOX
vzlADamInjv3h3EWHRF8Aphl+rwnQW11IZ+ybjkW5i+vxPkNKvj1i1ASug1STf6Lzc2u+wKS7+bK
UngkEMwDF+EFZlW8DQ4q98EZVezIINfY0Nx4YKDxSTODxGNonMZdZbd99Sirugqpd5qJbFvwlumg
tzEsAMfgZls4S4iQ6jNV4ki2YT7k/bRNqZMAc8Yd9Lq3udFfwkeHw54BNKGr7TahwIL8PniIXo8m
0AAQJeFZI1YkLCdBkiv9qWrhv7RgJkHKCDfxxSzpahH6Q7eQqe9RVeo7Y6slsJVc4fjyuZ+LnDvw
LzGOi+sStj8uYgZzLrtB0uMGwJOixViufEY8rrqAKPI553O8u5LLYbQfRKk8uIfH+T928JjEtTHh
Lb3cFJAXUs/EHHwRwgKicenMX/Igh/P1HjR0Jd/jtIQnZ7LLw+PK4qNmjf6KN82IlIFmtYket5ew
uelNx0thkEMM11NxevB1U/MVqKD4H9ugJSZhEorUXlwV00HfQfGqjVKvvCeIViAlbUYdzzgRjfWZ
yUJvZjKMk7Zm/ia9THeTRU6LgjRqaWH4d0OtMBYP75NnWxthuGWAJVIoTRU0EZC6CVkCfY+u/Sf2
RcCrWvlPhaEkiC0+Wlmnw0hP41qOz8p9lur37lzVN+bGqRB//bJ7ZUJWVHdZg30ZKWQjIEK5zE2G
7tHyZeqrPkTt4zN/1jJMrD4zQIa15oM0tWj/XUjEiIvMxoU0YYIkVyeW0QUis+MJvABo+QuoexRk
vw+96fpCXHgjtNXF3RNX4cmKXZFY9asCUbnwfXs0N0HxfV/6ZtImhH31SC4kl0D247tfT9Ru6pwC
9WOEVE6/Lpudpoah9BcseyVlLCFDLfZgmBo7ptR6aTGHiEG5+h9gqlqfR1EGTHDQ7l4gDUYi4rPR
5t1l9QL0EkFRzQZbFT9Kz51DPEMtuLwgdK1/g6RKV5+iD3IBsMheNOUWQzSfMdBNrhRzq1EVJnWs
/o/XIgiPZ2ySXuwBTEmNrN3J9AppcPhgK+27+A9/fBGixw2oT18CkGbvhrTNuG0BNGcI3js6ZWk8
a/bqY4gs1XeCVfmiT51XYSjM6UxfiwAotG/siroyhLviBXiJ90P2VUlN6SuVfxnr1A7DE5nsloQe
TCS9ITsqot+5ygoy1FkJuZMwP6jbwsK4iMo0FLnzZ2x8YVnF2X9ifOX0GAVGXru5QuQW1AD0jxny
G3G3ybsRWkqd2ewmRK25qaIfMb4ghLnsFtxlLZfoQDvW1vxN5koHFaw+fftvIYN3bJfFalmremoX
UfNP/nfhtJBdcfyeNv83LCmcCoGu9i1yXOE6haEW62MKVCxJZtcZO4c1ddNVIFwQihxQt+37zba6
JUnAHDglIpdy1rWJyhWPyEAkctmVJOlrBFnPipTKQlittE/y3O3q4egL4W97LXDtjx5z61465taO
1milYcSfvQTq4ey3B8VZqnC/QEMn7uZyVjMXZKuFRBDAPb/bAZCwpyvFfDm0Z3RdPjr+5It72s51
EXBHJn8b55JXW2NdVdvS/QR6D8C0DbwPST4pNitpcabcRee+55U29/jbKeP30ae618+SBMbjYtxq
pnKB3ffrUymwa+2yD+uC7qx9DapqFbZIeeqY4JCRO5KSOQYmLqsYtRmV6tf00z3VCNYaPXVshU9/
+j8TPQ+IxA3UJtbkSdN7WFywsFKgEwxrmx6cgNkpYSytPPNk9ZrzplWXP6UJ8DeIMJAW8e8psXSC
MTjmeMT5qIomTuLBp4IyyLwLukUtTqCfbU2KcbwGA1iB0WCQzmj1Di8D7IiFPrcnrnHdWtvlGgir
ACU0uCJI4GLx9guqSoEWKwFu/9Bj1NNGiItqpKurRQRmKhBw5BtL2/Nj6Y2iB7pUshGQPEOz37zZ
pEjLUzM0jkzoXRv3Jt+A4rYFb2e8P58+C+Dmk2GtWjuPG0qPb7clxfrzxk136I5XBmTYXDoE94Vy
LUyVybx84zV7f8vj3cQO3tGeqQdfSuDVtm8Nq5MGTQ1p2XfXlLwIJwk2JsAszevD8FG7MPVo0ugK
UYBNg9VjOKNF1zmom4/+rEMbzWOvPkdTTUHfwNWAGw4U5S741qTkxoqWXlQpfIbhrcyzRx6f9bgk
LJvaFR1lwwUexLaLxCOwMt9LU74j7CDU/mrevYMI5hSq1JLbcf08DCTiiBJ4LbfnjqtC6na+cvai
rBufxl+/OS/gqCLKCIXNybYymmmF82Sc9BJTy8r0yJhYw6uqswhDn2bmv7Pq6cKj38qOtSLZnO5Y
846FvKZ3P/VTvU5KHp88eW8z0EkH7k8dYan29txWx95w3z7ouf2XpX3OBQFCPJkVesMGZ/ovFskt
lVj4KcZXYf0V15h/7r7/7nUJpvLUQJDE7yYDt/o9JKKnBhUTBkyAiWxCsMGIeW+bPKl0a1dgj4qc
Dvm1pR2zBcU08TIGyRcGNmKXID3vz5qbGIxo26hwhbZxyiAWgP6bTnE50rq4qRc0uqVHk6sPwUhD
BgqDRMf76z8dC4XvvzrI9qhc8bMWoq84LPK7KmXiCS6FOOtLbeeu1jD+3GAdYHAdh/LfO8wZbqMr
gc1SyIjCL5tkKbVs3PztfPr25PqcNjY+mjSSEcNQOJuXOQ1kVex0lIpFz+Q8M/9U987vNo8HMSUr
s6kOms4tbXxAkBy1i+vjlpE2bOJmmvFXFRuhF+g15VyYLWlC7eFMClzybs0ge9XTbiMwvMZOWgxf
5w4UH7ihqsBUYx/hsD1lAlb253e13VWWKRSPX+s9KTXwIZMIHN747s64/HWHtYzu2vtys8a5W9ky
YPfzzxj7/KeuDJ7/oNXMWQmLT6TPgKmUcWB5Bu/c7fl3kdst6GoKgfrIV1xL3WZzqa9TQhW4iqQ+
C6Sorpj3SvziJUR6VIpaSh+0aEXBSWqJZUR7Lati6l2+l1gKSaOdIZBQhsdp9A6dqHZj1tT1Y6KT
T5k/LAiRTIyfSvPCsX97BFaccXjY/tlBVtqaKpIMEi2Zco2PB+H9bkKwa4LMdC6JLPqE4IGTItye
7hGzaMPfeY1+YLva3WPZe76jlsA0VRWOwm6BX2XtSzom0/vuCbexg32PKBZ287/PWMZzfImJLCYr
SnOf2f5qqGlNhk2A6ouzmNu0Ed9IfwrnA5P7DD414rSOPwVjGAhSnrHa4pQg13U+XLeYgbH6MVz7
NXZAeLSngU+I/+GV+EcIGBi5Qsoeoz8zoKJVbRxn1qENX19yela+6Ff2w4+Rtze5lU91x7gj9epE
7lyWmx/at67S3qRY1PqTLvyEY1QejgmsYcKa3WPt3qIzt3jVZhIygiPUKsgkFyyi7dyxTFgMZEGH
qWYNAoTrWhlrTiHQKxvM1B/BhNctxWWdED7rrIYnoDh8ZgwOVVt75S0oHaUMZ7ebiTu94Rju8wgD
dZccWn9YtsKG3NuibUFa0GIJ0li31ED3ZvwKDPf2RH0x46+KTwF+gtDsFeS6OAH6ZVqJCQhFITwj
EKzTqaF4Cs8VNpgBUEI1QbwbE7237VgnT66+mwR6CrihFI9/GMMHLjjDi3UJYw6cr+919fR9hhVD
ssJ1sE5S94x3eNcuM7sfYBS3/3FQJvB+DOEuhTExcubz8/Dh/dSlNdJe15Iom0EXlZjpehMtZA5Z
24yfaxgjLiKKgOCq7+J8i8l/rzdCL7joVipf8hM5hHzWfIqD9a54OVHmpkgvlRrRmtFfHwpPE4Hf
513T7z2cnvaGJCTKv8WdhYuNG4GWWY4itNqDxqAiTleP/qr48l4n92ELuM/7GfZj6VpqiY/WZkFc
p85ATVIoe5viSvXOZV51EfTLLImm37eHYKgnyZahjLeH3CZgjNd+XucFwdGdKU70kvlIhRgd3VIj
wH++t3f2ZnkBQoUvNX0qHlNBH+9bqEM9trzjLiY5pbM2A5stUS99WpJYT7gjDu9ocAj/iJM717WQ
Mn4YWTpAN9az2Lh2bFbW0FVcryU82WkfvGwvLwtwZA5+1UNbKno0gO+VMDFjWQ/AGQfi9suWgOF8
kEeTXC9an7UlXFBtzYvBgNC13idPulBKslqHE1msz+ISd6sFlYbO78023f71oEJd2eRfOKk0xmCA
lfm6ltIsSFFiWfYuyggZLtp44w5PhIAoVz8HJeZ2JWYvmMRShrB+xG2zRIiEAg2CP+8CHZv4wwfH
aJYNtHD/clcelBYEt0PhUa+efHwSJtlW/CkFEDFQDOFcesJQ6OIrHyJXfDbC2D1s+tQ9iAmJiicv
u3dVgP8Fja97UVCqY9P9C3r5IMf15QGoH32BYJdTkImuQCAo3DZ2BfePEOunFlcDC9zU2UG6DeGA
GesN5U0Sw+y3Dny0+VlNIK+KkZH8YOCTQxfBgb2gs1BHTA8wO1J9SA60nTHBFNFalSkvCYlJujVe
7LDPmMw0Pvuok43hrwtkHyVJ3lK3BfcCuHuI+vFWrc9DHtip5V+kRQ7bZtS54j5Txcp3fArVhyUX
jzLe5eoeT9z5JUwj/vcOYK+3dgh16T4xF+pYt2f6SdDsq3tZzvfbRCFsqLCFZeuCwcDhkREqMkdY
rYpSt/uGI/UZtHzSbjAgK7yt+dC0266I7oyzKo8LRvL7bAaHNIBB5ovR5Mku9pK1LumbVEgl51XF
boUwa9wupbz6rhn2UuI3twPuGea6897YsMKX0H62FYXH0NClvBCswfr8BDNKbIawBPF3r2DLDdHJ
3FVox/e/cA81gY89p4P0DtIp1kQNWS3jb5X00+3HzKDsuxJjE1rIdUrsLZCLLFHVmjkscrFkL3gk
E2EDmQv8iMyVR3H+ufBo76AhCckIo0WJI+yCxuOpvi9V+KgRXF/S0ECo+ghCP4i8yl71A7q1KBpp
j7akFib9RYzLO10vhmPqSCmQxCd5+cUkiz7offCKUmjxehrMq0/jNTsAcmHYLPDO8iWLD53Qn3A4
cVrB39+N1P90Y7IPsHqdTqNHgZWeMdxOL72ACqPO41fMftMrrFNQu7uT6L4ZZwASQb9BjPmxRa9W
QlME19YoL3sdCLJ1XmEggxl21N3OfFYyrd11UPTYGytFVcmGOw/usaiOPCGoBnRESbt1yoDvgFrt
wrs5ssuOK0/IUa05BNG/mGEieAlnssrVK0aSSVXwg6y5C4cD4AkyJcnX/VQ1ZXgqFw/8+/PDoVvS
brsRXH2HqkFhtMUEuKzt322oOKi3URKxoWyByzuNSvzejycBPHUPKOJrOmZDGqLkhP5WBypzkqM6
2xFPDiIwhv5NoVmNPejdgQMdsDkyN+X9fOoJFfM11OlK+FriUSOKW6VJlIGiwygF0kfwreD7Nkdl
PiLHSpktkSqgOK1rFMRJQgiEcsOcTuhnM98IX79UCBRgOg9Ve+8LeB+jyphYQ/53mHwA1gS9JOm2
0ekhc3evofwIkditPrOCldZD2NWpZHVMWsLnf3/zvjakrCGKpdaTjIZWNCzfAkkEOTD3LJtv8UvC
hiZnSMXS6fwFMWSQYghW95xWDtizx0Fq7QMfw7ReMfZbyrMiHFa/yhs/rZ6+vfQymGJcsRHtdKUK
BrmtpzpscG52tK/u7V51yKvBeE1EAJZmPYdsrH9VKJAPgNRhzkpr00Y0rba1ePxNRsTLN/9aD6vO
SZOQT8q7HLldMuSkIQGoHHL9CdsVFMV5+N5OY62N4teA2gAgy5Az17wmzPgRTdZ5KZBaKfqp2IWo
VpgLCvlEkb2duXHn8kYFogpYhg5uVjYQAA6JcAVYm1Ec8YXntp7fi+R4JjFQXyaFVFls8TBmWCww
3XUT3NIEmkjjf7YudAB0AlbzmsbUaNfKBq8BomKfccEIykfBy1Z2hUs47avxJ1mRrQUCul4DcEQH
qLYfH4OUFHVaV8XzRCOcambVrHoaDj+LSQSPQuvg0nrcXpWdvVprVeyzwCyshQC0XtDS2eLW04mk
DBbrZ7brM2uUMFoC/Q6LLjZmEO9uQwkCdOU6Axy0uzMBJhGONxqBh3hvpiijneZsKT15PE3RUvJh
yka4h8+Bt7faRE4o8BwFZuhVHal2qCeUgM7s51KO91Ib+cXWZSPqPhQ9Yy1eEn/t1rhLZYZjJ0ah
R7fmZn+Sfww3EsIDSBLnYbfeoc+KvEmYZh0Wk/60lUIM5ZZj0vCwDHQitCLZ4zXv/2afVgQdLwUi
6LXtGgZAetQDCwhYDhnssmfF2JfZUtUPhac1hN5Oh7n63qYY4KxzOulL9jOpLxd850q/DyiVvpgT
IaVG1USu4CEb7HuwaQUbs8/kiyQeqNviVwrtpn7suu5wW10bgG6T0llNJgV1xlAR0in0fEC4mVCx
QU7c4P4fBwOCzSV+rpZZ69zv9yz8zSJs4PlbSzn/6PW6D4vLSLapJGvjU1EzlX7UaamcbPJsvzz3
iH99ssbCUNoe15PckwCVu5yQjUzpUd6IXhQA74mZ4f6UNl3n7vFP4k3yqQF/zQ8wdWXEjh2tdE1K
wjJeb6i5TOxHNezeE8NauEDgqNBJ8q9jmF+jn5grRFOYyHdTnfrF0gkj539auqywKRQoM06ggblS
Zejx5lHUh8t/4xYaPK3D4GCipU9+DsEZ1CotQ58HhNeBD1oCPKVZeVTLoV58a740BrrPrYy8VVM+
Sp4A74UQCp94UMQvyuR6vZvAQORCa77MXpXsrY8RtTYjnGYTbSEABVR5tJc1nOrN/mYzLH+zUDO4
9bWh61h1A7xncyyYUzo0Af8WyUhL3CQoGTCd8siEht5vkKQUwlTmonhtGpyuMAdv1BkZXQv84UDy
BBy6jatWSsewvq0OfPyTnJKXvoVQT7/PdrxaVVk7JR18zofFMeJYf9HxtzGrRS04r/RR71YbFj2V
6aO/z4/L2Z7XTwHMfLOSCyWmxX2XbjCY1HQS2nXHWb471E9owgyH4r7Rnp5YStmZlH2PWXJ4Bl/z
FiAtAikUdm==

**Expected behaviour**
Segmation fault (Core dumped)

**Version information:**
 - PHP Version 7.4.28
 - VLD version 0.17.2
 -opcache Enabled

**Additional context**

**Comment by derickr** [comment]
I don't support ionCube.
