### ISSUE TITLE
Can I get internal_function's opcode by using vld?

### ISSUE THREAD

**Issue by Porlockzzz** [derickr/vld#80]
Dear Derick,

I'm interested in how some PHP internal functions work, and I want to know if I can get the opcode of PHP internal functions through vld? 

At present, I can only get the opcode of user-defined functions through vld. If it can't be obtained through vld, do you know any other way to get it?

Best wishes!

**Comment by derickr** [comment]
On Sat, 20 May 2023, DuckYellow wrote:

> I'm interested in how some PHP internal functions work, and I want to 
> know if I can get the opcode of PHP internal functions through vld?
> 
> At present, I can only get the opcode of user-defined functions 
> through vld. If it can't be obtained through vld, do you know any 
> other way to get it?

Only user land functions (written in PHP) will have opcodes. Internal 
functions are written in C, and hence don't have them. And therefore VLD 
can't show them. You can find the implementation of internal functions 
by searching for "PHP_FUNCTION" in the PHP source code.

cheers,
Derick

-- 
https://derickrethans.nl | https://xdebug.org | https://dram.io

Author of Xdebug. Like it? Consider supporting me: https://xdebug.org/support
Host of PHP Internals News: https://phpinternals.news

mastodon: @***@***.*** @***@***.***
twitter: @derickr and @xdebug

**Comment by Porlockzzz** [comment]
> 

Thanks!
