### ISSUE TITLE
Show type information for arguments for each oparray

### ISSUE THREAD

**Issue by Porlockzzz** [derickr/vld#81]
I'm interested in PHP opcode, when I use VLD to analyze a case, I found some interesting.
Below is the code for this case, these are two PHP files: main.php and include.php

![image](https://github.com/derickr/vld/assets/37264975/13476e6c-6b9e-4085-a0d7-75ad995a4fd9)

![image](https://github.com/derickr/vld/assets/37264975/7598f0bd-3775-4d02-bdb8-5ff58273f281)

Absolutely, after main.php execution, we get a different value for $var1 and $var2.
But, when I check the opcode, I found that the opcodes for function sendref and function sendnoref are the same.

![image](https://github.com/derickr/vld/assets/37264975/ba422e7e-acf0-4415-821c-8a5bbad745e6)

And for main.php, it seems that the opcode for the function call is the same too.

![image](https://github.com/derickr/vld/assets/37264975/43521225-f4b1-4d6d-af64-24b2feb4a42d)

So, I want to know why we get a different value for $var1 and $var2 when the opcodes are the same.

**Comment by jvoisin** [comment]
Please don't use screenshots for text when possible, it's not cool for a lot of people (blind users, terminal users, …)

**Comment by derickr** [comment]
There is no bug here.

The "referenceness" is not checked/done through the **opcode**, but instead this is part of the function signature. An op array contains for each argument "arg_info_flags" which contains which type the argument is supposed to be, and also whether it is a reference or a variadic.

- https://github.com/php/php-src/blob/PHP-8.2/Zend/zend_compile.c#L6881
- https://github.com/php/php-src/blob/PHP-8.2/Zend/zend_compile.c#L6956

VLD does not show this information to go with each function (oparray) yet.

**Comment by Porlockzzz** [comment]
> Please don't use screenshots for text when possible, it's not cool for a lot of people (blind users, terminal users, …)

Thanks for the reminder!

**Comment by Porlockzzz** [comment]
> There is no bug here.
> 
> The "referenceness" is not checked/done through the **opcode**, but instead this is part of the function signature. An op array contains for each argument "arg_info_flags" which contains which type the argument is supposed to be, and also whether it is a reference or a variadic.
> 
> * https://github.com/php/php-src/blob/PHP-8.2/Zend/zend_compile.c#L6881
> * https://github.com/php/php-src/blob/PHP-8.2/Zend/zend_compile.c#L6956
> 
> VLD does not show this information to go with each function (oparray) yet.

Thanks!
